namespace Airslip.Common.Types.Enums
{
    public enum PosProviders
    {
        SwanRetailMidas,
        Api2Cart,
        Volusion,
        Shopify,
        Stripe,
        SumUp,
        IZettle,
        EposNow,
        Square,
        Vend,
        Cart3D,
        Cart3DApi,
        AmazonSP,
        Amazon,
        Demandware,
        EBay,
        Etsy,
        EtsyAPIv3,
        Hybris,
        Magento,
        AspDotNetStorefront,
        CommerceHQ,
        Ecwid,
        Neto,
        LightSpeed,
        Prestashop,
        Squarespace,
        Shopware,
        ShopwareApi,
        Walmart,
        Woocommerce
    }
}
